version: '3.9'

services:
  flickr-service:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REDIS_URL: 'redis://redis:6379'
    networks: 
      - flickr-network
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0
    restart: always
    ports:
      - '6379:6379'
    networks: 
      - flickr-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks: 
  flickr-network:
    driver: bridge